<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE vtkConf [
    <!ELEMENT vtkConf (info, reference*, configuration*, module*)>
        <!ELEMENT info (vtkConfigurationsVersion,projectName)>
                <!ELEMENT vtkConfigurationsVersion (#PCDATA)>
                <!ELEMENT projectName (#PCDATA)>
        <!ELEMENT configuration (name,path,templatePath?,title?,comment?,password?)>
         <!ATTLIST configuration cID ID #REQUIRED>
         <!ATTLIST configuration refIDs IDREFS #IMPLIED>
                <!ELEMENT name (#PCDATA)>
                <!ELEMENT path (#PCDATA)>
                <!ELEMENT templatePath (#PCDATA)>
                <!ELEMENT title        (#PCDATA)>
                <!ELEMENT comment (#PCDATA)>
                <!ELEMENT password (#PCDATA)>
        <!ELEMENT module (name, modulePath*)>
         <!ATTLIST module mID ID #REQUIRED>
                <!ELEMENT modulePath (#PCDATA)>
                <!ATTLIST modulePath confId IDREF #REQUIRED>
        <!ELEMENT reference (name, (guid|path))>
         <!ATTLIST reference refID ID #REQUIRED>
                <!ELEMENT guid (#PCDATA)>
]>
<vtkConf>

    <info>
        <vtkConfigurationsVersion>2.0</vtkConfigurationsVersion>
        <projectName>VBAToolKit</projectName>
    </info>

    <reference refID="r1">
        <name>VBA</name>
        <guid>{000204EF-0000-0000-C000-000000000046}</guid>
    </reference>
    <reference refID="r2">
        <name>Excel</name>
        <guid>{00020813-0000-0000-C000-000000000046}</guid>
    </reference>
    <reference refID="r3">
        <name>stdole</name>
        <guid>{00020430-0000-0000-C000-000000000046}</guid>
    </reference>
    <reference refID="r4">
        <name>Office</name>
        <guid>{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}</guid>
    </reference>
    <reference refID="r5">
        <name>MSForms</name>
        <guid>{0D452EE1-E08F-101A-852E-02608C4D0BB4}</guid>
    </reference>
    <reference refID="r6">
        <name>Scripting</name>
        <guid>{420B2830-E718-11CF-893D-00A0C9054228}</guid>
    </reference>
    <reference refID="r7">
        <name>VBIDE</name>
        <guid>{0002E157-0000-0000-C000-000000000046}</guid>
    </reference>
    <reference refID="r8">
        <name>Shell32</name>
        <guid>{50A7E9B0-70EF-11D1-B75A-00A0C90564FE}</guid>
    </reference>
    <reference refID="r9">
        <name>MSXML2</name>
        <guid>{F5078F18-C551-11D3-89B9-0000F81FE221}</guid>
    </reference>
    <reference refID="r10">
        <name>ADODB</name>
        <guid>{00000206-0000-0010-8000-00AA006D2EA4}</guid>
    </reference>
    <reference refID="r11">
        <name>VBAToolKit</name>
        <path>C:\Documents and Settings\Demonn\Application Data\Microsoft\AddIns\VBAToolKit.xlam</path>
    </reference>
    <configuration cID="c1" refIDs="r1 r2 r3 r4 r5 r6 r7 r8 r9">
        <name>VBAToolKit</name>
        <path>Delivery\VBAToolKit.xlam</path>
        <title>VBAToolKit</title>
        <comment>ToolKit for improving VBA development. Add-In for Excel 2007 and above.</comment>
    </configuration>
    <configuration cID="c2" refIDs="r1 r2 r3 r4 r5 r6 r7 r8 r9 r11">
        <name>VBAToolKit_DEV</name>
        <path>Project\VBAToolKit_DEV.xlsm</path>
        <title>VBAToolKit_DEV</title>
        <comment>Development and Test version for VBAToolKit</comment>
    </configuration>
    <configuration cID="c3" refIDs="r1 r2 r3 r4 r5 r6 r7 r8 r9">
        <name>VBAToolKit_2003</name>
        <path>Delivery\VBAToolKit.xla</path>
        <title>VBAToolKit</title>
        <comment>ToolKit for improving VBA development. Add-In for Excel 2003.</comment>
    </configuration>
    <module mID="m1">
        <name>vtkImportExportUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkImportExportUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkImportExportUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkImportExportUtilities.bas</modulePath>
    </module>
    <module mID="m2">
        <name>vtkConstants</name>
        <modulePath confId="c1">Source\ConfProd\vtkConstants.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConstants.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConstants.bas</modulePath>
    </module>
    <module mID="m3">
        <name>vtkCreateProjectTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkCreateProjectTester.cls</modulePath>
    </module>
    <module mID="m4">
        <name>vtkPathUtilitiesTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkPathUtilitiesTester.cls</modulePath>
    </module>
    <module mID="m5">
        <name>vtkWorkbookIsOpenTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkWorkbookIsOpenTester.cls</modulePath>
    </module>
    <module mID="m6">
        <name>RunManager</name>
        <modulePath confId="c1">Source\VbaUnit\RunManager.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\RunManager.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\RunManager.cls</modulePath>
    </module>
    <module mID="m7">
        <name>TestCaseManager</name>
        <modulePath confId="c1">Source\VbaUnit\TestCaseManager.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestCaseManager.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestCaseManager.cls</modulePath>
    </module>
    <module mID="m8">
        <name>TestClassLister</name>
        <modulePath confId="c1">Source\VbaUnit\TestClassLister.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestClassLister.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestClassLister.cls</modulePath>
    </module>
    <module mID="m9">
        <name>TesterTemplate</name>
        <modulePath confId="c1">Source\VbaUnit\TesterTemplate.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TesterTemplate.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TesterTemplate.cls</modulePath>
    </module>
    <module mID="m10">
        <name>TestFailure</name>
        <modulePath confId="c1">Source\VbaUnit\TestFailure.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestFailure.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestFailure.cls</modulePath>
    </module>
    <module mID="m11">
        <name>TestResult</name>
        <modulePath confId="c1">Source\VbaUnit\TestResult.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestResult.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestResult.cls</modulePath>
    </module>
    <module mID="m12">
        <name>TestRunner</name>
        <modulePath confId="c1">Source\VbaUnit\TestRunner.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestRunner.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestRunner.cls</modulePath>
    </module>
    <module mID="m13">
        <name>TestSuite</name>
        <modulePath confId="c1">Source\VbaUnit\TestSuite.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestSuite.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestSuite.cls</modulePath>
    </module>
    <module mID="m14">
        <name>TestSuiteManager</name>
        <modulePath confId="c1">Source\VbaUnit\TestSuiteManager.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\TestSuiteManager.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\TestSuiteManager.cls</modulePath>
    </module>
    <module mID="m15">
        <name>VbaUnitMain</name>
        <modulePath confId="c1">Source\VbaUnit\VbaUnitMain.bas</modulePath>
        <modulePath confId="c2">Source\VbaUnit\VbaUnitMain.bas</modulePath>
        <modulePath confId="c3">Source\VbaUnit\VbaUnitMain.bas</modulePath>
    </module>
    <module mID="m16">
        <name>Assert</name>
        <modulePath confId="c1">Source\VbaUnit\Assert.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\Assert.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\Assert.cls</modulePath>
    </module>
    <module mID="m17">
        <name>AutoGen</name>
        <modulePath confId="c1">Source\VbaUnit\AutoGen.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\AutoGen.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\AutoGen.cls</modulePath>
    </module>
    <module mID="m18">
        <name>IAssert</name>
        <modulePath confId="c1">Source\VbaUnit\IAssert.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\IAssert.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\IAssert.cls</modulePath>
    </module>
    <module mID="m19">
        <name>IResultUser</name>
        <modulePath confId="c1">Source\VbaUnit\IResultUser.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\IResultUser.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\IResultUser.cls</modulePath>
    </module>
    <module mID="m20">
        <name>IRunManager</name>
        <modulePath confId="c1">Source\VbaUnit\IRunManager.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\IRunManager.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\IRunManager.cls</modulePath>
    </module>
    <module mID="m21">
        <name>ITest</name>
        <modulePath confId="c1">Source\VbaUnit\ITest.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\ITest.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\ITest.cls</modulePath>
    </module>
    <module mID="m22">
        <name>ITestCase</name>
        <modulePath confId="c1">Source\VbaUnit\ITestCase.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\ITestCase.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\ITestCase.cls</modulePath>
    </module>
    <module mID="m23">
        <name>ITestManager</name>
        <modulePath confId="c1">Source\VbaUnit\ITestManager.cls</modulePath>
        <modulePath confId="c2">Source\VbaUnit\ITestManager.cls</modulePath>
        <modulePath confId="c3">Source\VbaUnit\ITestManager.cls</modulePath>
    </module>
    <module mID="m24">
        <name>vtkConfigurationManager</name>
        <modulePath confId="c1">Source\ConfProd\vtkConfigurationManager.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConfigurationManager.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConfigurationManager.cls</modulePath>
    </module>
    <module mID="m25">
        <name>vtkConfManagerExcel10Tester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfManagerExcel10Tester.cls</modulePath>
    </module>
    <module mID="m26">
        <name>vtkConfManagerExcel11Tester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfManagerExcel11Tester.cls</modulePath>
    </module>
    <module mID="m27">
        <name>vtkConfManagerExcel12Tester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfManagerExcel12Tester.cls</modulePath>
    </module>
    <module mID="m28">
        <name>vtkConfigurationManagers</name>
        <modulePath confId="c1">Source\ConfProd\vtkConfigurationManagers.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConfigurationManagers.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConfigurationManagers.bas</modulePath>
    </module>
    <module mID="m29">
        <name>vtkConfigurationManagersTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfigurationManagersTester.cls</modulePath>
    </module>
    <module mID="m30">
        <name>vtkProjects</name>
        <modulePath confId="c1">Source\ConfProd\vtkProjects.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkProjects.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkProjects.bas</modulePath>
    </module>
    <module mID="m31">
        <name>vtkProject</name>
        <modulePath confId="c1">Source\ConfProd\vtkProject.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkProject.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkProject.cls</modulePath>
    </module>
    <module mID="m32">
        <name>vtkProjectsTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkProjectsTester.cls</modulePath>
    </module>
    <module mID="m33">
        <name>vtkProjectTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkProjectTester.cls</modulePath>
    </module>
    <module mID="m34">
        <name>vtkInitializeVbaUnitTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkInitializeVbaUnitTester.cls</modulePath>
    </module>
    <module mID="m35">
        <name>vtkExcelUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkExcelUtilities2007.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkExcelUtilities2007.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkExcelUtilities2003.bas</modulePath>
    </module>
    <module mID="m36">
        <name>vtkProjectCreationUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkProjectCreationUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkProjectCreationUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkProjectCreationUtilities.bas</modulePath>
    </module>
    <module mID="m37">
        <name>vtkMainFunctions</name>
        <modulePath confId="c1">Source\ConfProd\vtkMainFunctions.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkMainFunctions.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkMainFunctions.bas</modulePath>
    </module>
    <module mID="m38">
        <name>vtkCreateTreeFolderTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkCreateTreeFolderTester.cls</modulePath>
    </module>
    <module mID="m39">
        <name>vtkImportExportUtilitiesTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkImportExportUtilitiesTester.cls</modulePath>
    </module>
    <module mID="m40">
        <name>vtkPathUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkPathUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkPathUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkPathUtilities.bas</modulePath>
    </module>
    <module mID="m41">
        <name>vtkEventHandler</name>
        <modulePath confId="c1">Source\ConfProd\vtkEventHandler.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkEventHandler.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkEventHandler.cls</modulePath>
    </module>
    <module mID="m42">
        <name>vtkToolBars</name>
        <modulePath confId="c1">Source\ConfProd\vtkToolBars.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkToolBars.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkToolBars.bas</modulePath>
    </module>
    <module mID="m43">
        <name>vtkToolBarsTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkToolBarsTester.cls</modulePath>
    </module>
    <module mID="m44">
        <name>ThisWorkbook</name>
        <modulePath confId="c1">Source\ConfProd\ThisWorkbook.cls</modulePath>
        <modulePath confId="c2">Source\ConfTest\ThisWorkbook.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\ThisWorkbook.cls</modulePath>
    </module>
    <module mID="m45">
        <name>vtkCreateProjectForm</name>
        <modulePath confId="c1">Source\ConfProd\vtkCreateProjectForm.frm</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkCreateProjectForm.frm</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkCreateProjectForm.frm</modulePath>
    </module>
    <module mID="m46">
        <name>vtkExportOneModuleTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkExportOneModuleTester.cls</modulePath>
    </module>
    <module mID="m47">
        <name>vtkGitFunctions</name>
        <modulePath confId="c1">Source\ConfProd\vtkGitFunctions.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkGitFunctions.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkGitFunctions.bas</modulePath>
    </module>
    <module mID="m48">
        <name>vtkGitFunctionsTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkGitFunctionsTester.cls</modulePath>
    </module>
    <module mID="m49">
        <name>vtkFileSystemUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkFileSystemUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkFileSystemUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkFileSystemUtilities.bas</modulePath>
    </module>
    <module mID="m50">
        <name>vtkFileSystemUtilitiesTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkFileSystemUtilitiesTester.cls</modulePath>
    </module>
    <module mID="m51">
        <name>vtkShellAndWait</name>
        <modulePath confId="c1">Source\ConfProd\vtkShellAndWait.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkShellAndWait.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkShellAndWait.bas</modulePath>
    </module>
    <module mID="m52">
        <name>vtkConfiguration</name>
        <modulePath confId="c1">Source\ConfProd\vtkConfiguration.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConfiguration.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConfiguration.cls</modulePath>
    </module>
    <module mID="m53">
        <name>vtkConfigurationTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfigurationTester.cls</modulePath>
    </module>
    <module mID="m54">
        <name>vtkModule</name>
        <modulePath confId="c1">Source\ConfProd\vtkModule.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkModule.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkModule.cls</modulePath>
    </module>
    <module mID="m55">
        <name>vtkModuleTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkModuleTester.cls</modulePath>
    </module>
    <module mID="m56">
        <name>vtkTestUtilities</name>
        <modulePath confId="c1">Source\ConfTest\vtkTestUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfTest\vtkTestUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfTest\vtkTestUtilities.bas</modulePath>
    </module>
    <module mID="m57">
        <name>vtkExportConfigurationTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkExportConfigurationTester.cls</modulePath>
    </module>
    <module mID="m58">
        <name>vtkNormalize</name>
        <modulePath confId="c1">Source\ConfProd\vtkNormalize.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkNormalize.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkNormalize.bas</modulePath>
    </module>
    <module mID="m59">
        <name>vtkNormalizeTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkNormalizeTester.cls</modulePath>
    </module>
    <module mID="m60">
        <name>vtkTestUtilitiesTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkTestUtilitiesTester.cls</modulePath>
    </module>
    <module mID="m61">
        <name>vtkXMLUtilities</name>
        <modulePath confId="c1">Source\ConfProd\vtkXMLUtilities.bas</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkXMLUtilities.bas</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkXMLUtilities.bas</modulePath>
    </module>
    <module mID="m62">
        <name>vtkXMLExportTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkXMLExportTester.cls</modulePath>
    </module>
    <module mID="m63">
        <name>vtkRecreateConfExcelTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkRecreateConfExcelTester.cls</modulePath>
    </module>
    <module mID="m64">
        <name>vtkRecreateConfigurationForm</name>
        <modulePath confId="c1">Source\ConfProd\vtkRecreateConfigurationForm.frm</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkRecreateConfigurationForm.frm</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkRecreateConfigurationForm.frm</modulePath>
    </module>
    <module mID="m65">
        <name>vtkExcelUtilitiesTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkExcelUtilitiesTester.cls</modulePath>
    </module>
    <module mID="m66">
        <name>vtkReferenceManager</name>
        <modulePath confId="c1">Source\ConfProd\vtkReferenceManager.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkReferenceManager.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkReferenceManager.cls</modulePath>
    </module>
    <module mID="m67">
        <name>vtkReferenceManagerTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkReferenceManagerTester.cls</modulePath>
    </module>
    <module mID="m68">
        <name>vtkReference</name>
        <modulePath confId="c1">Source\ConfProd\vtkReference.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkReference.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkReference.cls</modulePath>
    </module>
    <module mID="m69">
        <name>vtkConfigurationManagerExcel</name>
        <modulePath confId="c1">Source\ConfProd\vtkConfigurationManagerExcel.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConfigurationManagerExcel.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConfigurationManagerExcel.cls</modulePath>
    </module>
    <module mID="m70">
        <name>vtkConfigurationManagerXML</name>
        <modulePath confId="c1">Source\ConfProd\vtkConfigurationManagerXML.cls</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkConfigurationManagerXML.cls</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkConfigurationManagerXML.cls</modulePath>
    </module>
    <module mID="m71">
        <name>vtkConfManagerXML20Tester</name>
        <modulePath confId="c2">Source\ConfTest\vtkConfManagerXML20Tester.cls</modulePath>
    </module>
    <module mID="m72">
        <name>vtkRecreateConfXMLTester</name>
        <modulePath confId="c2">Source\ConfTest\vtkRecreateConfXMLTester.cls</modulePath>
    </module>
    <module mID="m73">
        <name>vtkWaitForm</name>
        <modulePath confId="c1">Source\ConfProd\vtkWaitForm.frm</modulePath>
        <modulePath confId="c2">Source\ConfProd\vtkWaitForm.frm</modulePath>
        <modulePath confId="c3">Source\ConfProd\vtkWaitForm.frm</modulePath>
    </module>
</vtkConf>
